services:
  db:
    image: postgres:17-alpine
    container_name: clinic_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - clinic_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clinic_net

  backend:
    build: ./backend
    container_name: clinic_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
      - PORT=5000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - clinic_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: clinic_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinic.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - clinic_net
    depends_on:
      - db

networks:
  clinic_net:
    driver: bridge

volumes:
  clinic_data:
